---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyr)
library(dplyr)

lines <- readLines('day5input') %>% gsub(pattern = " -> ", " ", .) %>% gsub(pattern=",", " ", .) %>% textConnection() %>% 
  read.table(col.names = c("x1","y1", "x2","y2")) %>%  transmute(Z1=x1*(1+0i)+y1*(0+1i), Z2=x2*(1+0i)+y2*(0+1i)) %>%  mutate(straight=Re(Z1) == Re(Z2) | Im(Z1) == Im(Z2)) 

rowcombs <- combn(NROW(lines), 2) # every distinct combination of 2 rows
```

```{r}
colinear <- function(z1, z2, z3, givepos=F){
  lambda <- (z1-z3)/(z3-z2)
  return(Im(lambda)==0) 
}

splitc <- function(Z){
  return(c(Re(Z),Im(Z)))
}
overlap <- function(x,y){ #need to add diagonals
  
  if (var(x)==0 & any(y[1:2] %in% y[3]:y[4], y[3:4] %in% y[1]:y[2])){ #if  vertical and overlaps
    seg <- sort(y)
    points <- seq(seg[2],seg[3],by=1)*(0+1i)+x[1]*(1+0i)
    return(points)
  }else if (var(y)==0 & any(x[1:2] %in% x[3]:x[4], x[3:4] %in% x[1]:x[2])){ #if horizontal and overlaps
    seg <- sort(x)
    points <- seq(seg[2],seg[3],by=1)*(1+0i)+y[1]*(0+1i)
    return(points)
  }else{
    return(NA)
  }
}

lineintercept <- function (Z1,Z2,Z3,Z4, segment = T){
  P1 <- splitc(Z1) #get point pairs from cmplx coordinates
  P2 <- splitc(Z2)
  P3 <- splitc(Z3)
  P4 <- splitc(Z4)
  dx1 <- P1[1] - P2[1]
  dx2 <- P3[1] - P4[1]
  dy1 <- P1[2] - P2[2]
  dy2 <- P3[2] - P4[2]
  D <- det(rbind(c(dx1, dy1), c(dx2, dy2)))
  if (D == 0) {
    return(c(Inf, Inf))
  }
  D1 <- det(rbind(P1, P2))
  D2 <- det(rbind(P3, P4))
  X <- det(rbind(c(D1, dx1), c(D2, dx2)))/D
  Y <- det(rbind(c(D1, dy1), c(D2, dy2)))/D
  if (segment) {
    lambda1 <- -((X - P1[1]) * dx1 + (Y - P1[2]) * dy1)/(dx1^2 + 
      dy1^2)

    lambda2 <- -((X - P3[1]) * dx2 + (Y - P3[2]) * dy2)/(dx2^2 + 
      dy2^2)
    lambda1 <- round(lambda1,digits=4)
    lambda2 <- round(lambda2, digits=4)
    if (any(lambda1>1,lambda1<0,lambda2>1,lambda2<0)) {
      return(c(NA, NA))
    }
  }
  return(c(X, Y))
}
```

```{r}
points <- data.frame(C=complex(), L1=numeric(), L2=numeric(), straight=logical())
for (i in 1:NCOL(rowcombs)){
  L1i <- rowcombs[1,i]
  L2i <- rowcombs[2,i]
  
  L1 <- lines[L1i,]
  L2 <- lines[L2i,]
  x <- c(L1$Z1, L1$Z2, L2$Z1, L2$Z2) %>% Re()
  y <- c(L1$Z1, L1$Z2, L2$Z1, L2$Z2) %>% Im()
  
  point <- lineintercept(L1$Z1, L1$Z2, L2$Z1, L2$Z2)
  
  if (colinear(L1$Z1, L1$Z2, L2$Z1) & colinear(L1$Z2,L2$Z1, L2$Z2)){ #if two lines are colinear
    points.temp <- overlap(x,y)
    if (any(is.na(points.temp))){next} #skip if segments dont overlap
    points <- rbind(points, data.frame(C=points.temp,L1=L1i, L2=L2i, straight=L1$straight & L2$straight))
    next
  }else if (any(is.na(point), is.infinite(point))){ #skip non-intersecting segments
    next
  }else{
    points <- rbind(points, data.frame(C=point[1]*(1+0i)+point[2]*(0+1i),L1=L1i,L2=L2i,straight=L1$straight & L2$straight))
  }
}
points <- mutate(points, C = round(C,digits=2)) #fixes weird floating point issue
```

```{r}
spoints <- points[points$straight,]
t1 <- spoints %>% select(C) %>% count(C)
(Part1Ans <- NROW(t1))
```

```{r}
t2 <- points %>% select(C) %>% count(C)
(Part2Ans <- NROW(t2))
```

