---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(stringi)
rm(list=ls())
```

```{r}
bins <- read.fwf('day3input', widths=rep(1,12))
binsC <- scan('day3input', what="character", quiet=T)

```

```{r}
MCB.f <- function(x) {
  
  MCB <- as.numeric(colMeans(x) >= 0.5)
  return(MCB)
}
LCB.f <- function(x){
  LCB <- 1-MCB.f(x)
  return(LCB)
}

```


```{r}
gamma <- MCB.f(bins) %>% paste(collapse ="") %>% strtoi(base=2)
epsilon <- LCB.f(bins) %>% paste(collapse ="") %>% strtoi(base=2)

(Part1Ans <- gamma*epsilon)
```

```{r}
OGR <- bins #Oxygen Generator Rating

i <- 1
while(NROW(OGR) > 1 && i<=12){
  MCB <- MCB.f(OGR)
  rows <- which(OGR[,i] == MCB[i])
  OGR <- OGR[rows,]
  i <- i+1
}
OGR <- OGR %>% paste(collapse ="") %>% strtoi(base=2)
```


```{r}
CO2 <- bins #CO2 Scrubbing Rating

i <- 1
while(NROW(CO2) > 1 && i<=12){
  LCB <- LCB.f(CO2)
  rows <- which(CO2[,i] == LCB[i])
  CO2 <- CO2[rows,]
  i <- i+1
}
CO2 <- CO2 %>% paste(collapse ="") %>% strtoi(base=2)
```

```{r}
(Part2Ans <- OGR*CO2)
```

